Testing new quarto-publish.yml

diff --git a/quarto-publish.yml b/quarto-publish.yml
--- a/quarto-publish.yml
+++ b/quarto-publish.yml
@@ -8,15 +8,20 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
 
       - name: Setup R
         uses: r-lib/actions/setup-r@v2
 
       - name: Install Quarto
         run: |
-          curl -LO https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.deb
-          sudo dpkg -i quarto-linux-amd64.deb
+          curl -fsSL -o quarto-linux-amd64.deb https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.deb
+          if [ -s quarto-linux-amd64.deb ]; then
+            sudo dpkg -i quarto-linux-amd64.deb
+          else
+            echo "Failed to download Quarto CLI package."
+            exit 1
+          fi
 
       - name: Render Quarto Project
         run: quarto render --to html
@@ -27,3 +32,4 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./_site
           publish_branch: gh-pages
+
